apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-webmvc
  name: {{ .Release.Name}}-webmvc
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name}}-webmvc
status:
  loadBalancer: {}
