apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-auditlog-grpc
  name: {{ .Release.Name}}-auditlog-grpc
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: {{ .Release.Name}}-auditlog-grpc
status:
  loadBalancer: {}
