# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryEndpoint: 'classifiedads'
  dockerComposeFile: 'src/Monolith/docker-compose.yml'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloud
  displayName: SonarCloud
  jobs:  
  - job: SonarCloud
    displayName: SonarCloud
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'phongnguyend'
        scannerMode: 'MSBuild'
        projectKey: 'Practical.CleanArchitecture'
        projectName: 'Practical.CleanArchitecture'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Monolith/ClassifiedAds.Monolith.sln'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: WhiteSourceBolt
  displayName: Build and Run WhiteSource Bolt
  jobs:  
  - job: WhiteSourceBolt
    displayName: Build and Run WhiteSource Bolt
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Monolith/ClassifiedAds.Monolith.sln'
    - task: WhiteSource Bolt@20
      inputs:
        cwd: 'src/Monolith/'

- stage: DotNetBuild
  displayName: .Net Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: UseDotNet@2
        displayName: Use .Net 5.0.200
        inputs:
          packageType: 'sdk'
          version: '5.0.200'
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: 'src/Monolith/ClassifiedAds.Monolith.sln'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: dotnet list package --vulnerable
        inputs:
          command: 'custom'
          custom: 'list'
          arguments: 'package --vulnerable'
          workingDirectory: 'src/Monolith'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          arguments: '--configuration Release'
          workingDirectory: 'src/Monolith'
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: 'test'
          projects: |
            src/Monolith/ClassifiedAds.ArchTests/*.csproj
            src/Monolith/ClassifiedAds.ContractTests/*.csproj
            src/Monolith/ClassifiedAds.UnitTests/*.csproj
          arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      - task: reportgenerator@4
        displayName: Generate Test Report
        inputs:
          reports: '$(Build.SourcesDirectory)/**/*.cobertura.xml'
          targetdir: '$(Build.SourcesDirectory)/CoverageResults'
          assemblyfilters: '+ClassifiedAds.Application;+ClassifiedAds.Domain'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Build.SourcesDirectory)/CoverageResults/Cobertura.xml'
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            src/Monolith/ClassifiedAds.BackgroundServer/*.csproj
            src/Monolith/ClassifiedAds.GraphQL/*.csproj
            src/Monolith/ClassifiedAds.Migrator/*.csproj
            src/Monolith/ClassifiedAds.NotificationServer/*.csproj
            src/Monolith/ClassifiedAds.WebAPI/*.csproj
            src/Monolith/ClassifiedAds.IdentityServer/*.csproj
            src/Monolith/ClassifiedAds.WebMVC/*.csproj
            src/Monolith/ClassifiedAds.BlazorServerSide/*.csproj
            src/Monolith/ClassifiedAds.BlazorWebAssembly/*.csproj
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Monolith'
          publishLocation: 'Container'

- stage: DockerBuild
  displayName: Build and Push Docker Images
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Build services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: $(dockerRegistryEndpoint)
        dockerComposeFile: $(dockerComposeFile)
        action: 'Push services'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)