version: "3.6"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        ports:
            - "1434:1433"
        environment:
            SA_PASSWORD: "sqladmin123!@#"
            MSSQL_PID: "Developer"
            ACCEPT_EULA: "Y"
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
    mailhog:
        image: mailhog/mailhog
        ports: 
          - 1025:1025 # smtp server
          - 8025:8025 # web ui
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
          - zookeeper
        ports:
          - 9092:9092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    migrator:
        image: classifiedads.migrator
        build:
          context: .
          dockerfile: ./ClassifiedAds.Migrator/Dockerfile
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\Migrator:/ClassifiedAds.Monolith/logs
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          CheckDependency__Enabled: "true"
          CheckDependency__Host: "db:1433"
    identityserver:
        image: classifiedads.identityserver
        build:
          context: .
          dockerfile: ./ClassifiedAds.IdentityServer/Dockerfile
        ports:
            - "9000:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\IdentityServer:/ClassifiedAds.Monolith/logs
        depends_on:
          - db
          - migrator
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          CookiePolicyOptions__IsEnabled: "true"
          CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
          CookiePolicyOptions__Secure: "None"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          MessageBroker__AzureQueue__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
    notificationserver:
        image: classifiedads.notificationserver
        build:
          context: .
          dockerfile: ./ClassifiedAds.NotificationServer/Dockerfile
        ports:
            - "9001:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\NotificationServer:/ClassifiedAds.Monolith/logs
        depends_on:
          - db
          - migrator
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    webapi:
        image: classifiedads.webapi
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebAPI/Dockerfile
        ports:
            - "9002:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\WebAPI:/ClassifiedAds.Monolith/logs
            - D:\\ClassifiedAds.Monolith\\Files:/files
        depends_on:
          - db
          - migrator
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
          Storage__Provider: "Local"
          Storage__Local__Path: "/files"
          Storage__Azure__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          Storage__Azure__Container: "classifiedadds"
          Storage__Amazon__AccessKeyID: "xxx"
          Storage__Amazon__SecretAccessKey: "xxx"
          Storage__Amazon__BucketName: "classifiedadds"
          Storage__Amazon__RegionEndpoint: "ap-southeast-1"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          MessageBroker__Kafka__BootstrapServers: "kafka:9092"
          MessageBroker__AzureQueue__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
    webmvc:
        image: classifiedads.webmvc
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebMVC/Dockerfile
        ports:
            - "9003:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Files:/files
            - D:\\ClassifiedAds.Monolith\\Logs\\WebMVC:/ClassifiedAds.Monolith/logs
        depends_on:
          - db
          - migrator
          - rabbitmq
          - kafka
          - identityserver
          - webapi
          - notificationserver
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          CookiePolicyOptions__IsEnabled: "true"
          CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
          CookiePolicyOptions__Secure: "None"          
          CheckDependency__Enabled: "true"
          CheckDependency__Host: "migrator:80"
          OpenIdConnect__Authority: "http://host.docker.internal:9000"
          OpenIdConnect__RequireHttpsMetadata: "false"
          ResourceServer__Endpoint: "http://webapi"
          ResourceServer__PublicEndpoint: "http://host.docker.internal:9002"
          NotificationServer__Endpoint: "http://notificationserver"
          NotificationServer__PublicEndpoint: "http://localhost:9001"
          BackgroundServer__Endpoint: "http://backgroundserver"
          CurrentUrl: "http://host.docker.internal:9003"
          Storage__Provider: "Local"
          Storage__Local__Path: "/files"
          Storage__Azure__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          Storage__Azure__Container: "classifiedadds"
          Storage__Amazon__AccessKeyID: "xxx"
          Storage__Amazon__SecretAccessKey: "xxx"
          Storage__Amazon__BucketName: "classifiedadds"
          Storage__Amazon__RegionEndpoint: "ap-southeast-1"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          MessageBroker__Kafka__BootstrapServers: "kafka:9092"
          MessageBroker__AzureQueue__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
    blazor:
        image: classifiedads.blazor
        build:
          context: .
          dockerfile: ./ClassifiedAds.Blazor/Dockerfile
        ports:
            - "9008:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\Blazor:/ClassifiedAds.Monolith/logs
        depends_on:
          - identityserver
          - webapi
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          OpenIdConnect__Authority: "http://host.docker.internal:9000"
          OpenIdConnect__RequireHttpsMetadata: "false"
          ResourceServer__Endpoint: "http://webapi"
          ResourceServer__PublicEndpoint: "http://host.docker.internal:9002"
          CookiePolicyOptions__IsEnabled: "true"
          CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
          CookiePolicyOptions__Secure: "None" 
    backgroundserver:
        image: classifiedads.backgroundserver
        build:
          context: .
          dockerfile: ./ClassifiedAds.BackgroundServer/Dockerfile
        ports:
            - "9004:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\BackgroundServer:/ClassifiedAds.Monolith/logs
        depends_on:
          - db
          - migrator
          - rabbitmq
          - mailhog
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          CheckDependency__Enabled: "true"
          CheckDependency__Host: "migrator:80,rabbitmq:5672"
          NotificationServer__Endpoint: "http://notificationserver"
          MessageBroker__Provider: "RabbitMQ"
          MessageBroker__RabbitMQ__HostName: "rabbitmq"
          MessageBroker__Kafka__BootstrapServers: "kafka:9092"
          MessageBroker__AzureQueue__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          Notification__Email__Provider: "SmtpClient"
          Notification__Email__SmtpClient__Host: "mailhog"
          Notification__Email__SmtpClient__Port: "1025"
          Notification__Sms__Provider: "Fake"
          Notification__Sms__Twilio__AccountSId: ""
          Notification__Sms__Twilio__AuthToken: ""
          Notification__Sms__Twilio__FromNumber: ""
    graphql:
        image: classifiedads.graphql
        build:
          context: .
          dockerfile: ./ClassifiedAds.GraphQL/Dockerfile
        ports:
            - "9006:80"
        volumes:
            - D:\\ClassifiedAds.Monolith\\Logs\\GraphQL:/ClassifiedAds.Monolith/logs
        depends_on:
          - webapi
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ResourceServer__Endpoint: "http://webapi"
          ResourceServer__PublicEndpoint: "http://host.docker.internal:9002"
