apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-api
  name: identity-api
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: identity-api
status:
  loadBalancer: {}
