apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-grpc
  name: identity-grpc
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: identity-grpc
status:
  loadBalancer: {}
