apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-api
  name: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        envFrom:
        - configMapRef:
            name: shared
        - configMapRef:
            name: notification
        image: phongnguyend/classifiedads.services.notification.api
        name: notification-api
        resources: {}
      restartPolicy: Always
status: {}
