apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocelot
  name: ocelot
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ocelot
status:
  loadBalancer: {}
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocelot
  name: ocelot-public
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ocelot
status:
  loadBalancer: {}