apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-api
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  strategy: {}
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        envFrom:
        - configMapRef:
            name: shared
        - configMapRef:
            name: storage
        image: phongnguyend/classifiedads.services.storage.api
        name: storage-api
        resources: {}
      restartPolicy: Always
status: {}
