apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Ocelot__DefaultDownstreamScheme: "http"
  Ocelot__Routes__Products__Downstream: "http://product-api"
  Ocelot__Routes__Files__Downstream: "http://storage-api"
  Ocelot__Routes__AuditLogs__Downstream: "http://auditlog-api"
  Ocelot__Routes__Users__Downstream: "http://identity-api"
  Ocelot__Routes__Configurations__Downstream: "http://configuration-api"
  Ocelot__Routes__Hubs__Downstream: "ws://notification-api"