apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  strategy: {}
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        envFrom:
        - configMapRef:
            name: webapi
        image: phongnguyend/classifiedads.gateways.webapi
        name: webapi
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
