apiVersion: v1
kind: Service
metadata:
  labels:
    app: backgroundserver
  name: backgroundserver
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: backgroundserver
status:
  loadBalancer: {}
