apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blazor
  name: blazor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor
  strategy: {}
  template:
    metadata:
      labels:
        app: blazor
    spec:
      containers:
      - env:
        - name: CookiePolicyOptions__IsEnabled
          value: "true"
        - name: CookiePolicyOptions__MinimumSameSitePolicy
          value: Lax
        - name: CookiePolicyOptions__Secure
          value: None
        - name: OpenIdConnect__Authority
          value: http://identityserver
        - name: OpenIdConnect__RequireHttpsMetadata
          value: "false"
        - name: ResourceServer__Endpoint
          value: http://webapi
        - name: ResourceServer__PublicEndpoint
          value: http://host.docker.internal:9002
        image: phongnguyend/classifiedads.blazor
        name: blazor
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
