apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql
  name: graphql
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: graphql
status:
  loadBalancer: {}
