apiVersion: v1
kind: ConfigMap
metadata:
  name: identityserver
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  CookiePolicyOptions__IsEnabled: "true"
  CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
  CookiePolicyOptions__Secure: "None"
