apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-webapi
  name: {{ .Release.Name}}-webapi
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name}}-webapi
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-webapi
  name: {{ .Release.Name}}-webapi-public
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name}}-webapi
status:
  loadBalancer: {}