apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-db
  name: {{ .Release.Name}}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-db
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          value: sqladmin123!@#
        image: mcr.microsoft.com/mssql/server:2017-latest
        name: {{ .Release.Name}}-db
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
status: {}
