apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-db
  name: {{ .Release.Name}}-db
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    app: {{ .Release.Name}}-db
status:
  loadBalancer: {}
