apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-mailhog
  name: {{ .Release.Name}}-mailhog
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  - name: "8025"
    port: 8025
    targetPort: 8025
  selector:
    app: {{ .Release.Name}}-mailhog
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-mailhog
  name: {{ .Release.Name}}-mailhog-public
spec:
  type: LoadBalancer
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  - name: "8025"
    port: 8025
    targetPort: 8025
  selector:
    app: {{ .Release.Name}}-mailhog
status:
  loadBalancer: {}