apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-webapi
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Routes__0__DownstreamScheme: "http"
  Routes__0__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  Routes__0__DownstreamHostAndPorts__0__Port: "80"
  Routes__1__DownstreamScheme: "http"
  Routes__1__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  Routes__1__DownstreamHostAndPorts__0__Port: "80"
  Routes__2__DownstreamScheme: "http"
  Routes__2__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  Routes__2__DownstreamHostAndPorts__0__Port: "80"
  Routes__3__DownstreamScheme: "http"
  Routes__3__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  Routes__3__DownstreamHostAndPorts__0__Port: "80"
  Routes__4__DownstreamScheme: "http"
  Routes__4__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  Routes__4__DownstreamHostAndPorts__0__Port: "80"
  Routes__5__DownstreamScheme: "http"
  Routes__5__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  Routes__5__DownstreamHostAndPorts__0__Port: "80"
  Routes__6__DownstreamScheme: "http"
  Routes__6__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  Routes__6__DownstreamHostAndPorts__0__Port: "80"
  Routes__7__DownstreamScheme: "http"
  Routes__7__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  Routes__7__DownstreamHostAndPorts__0__Port: "80"
  Routes__8__DownstreamScheme: "http"
  Routes__8__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  Routes__8__DownstreamHostAndPorts__0__Port: "80"
  Routes__9__DownstreamScheme: "http"
  Routes__9__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  Routes__9__DownstreamHostAndPorts__0__Port: "80"
  Routes__10__DownstreamScheme: "http"
  Routes__10__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  Routes__10__DownstreamHostAndPorts__0__Port: "80"
  Routes__11__DownstreamScheme: "http"
  Routes__11__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  Routes__11__DownstreamHostAndPorts__0__Port: "80"
  Routes__12__DownstreamScheme: "http"
  Routes__12__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  Routes__12__DownstreamHostAndPorts__0__Port: "80"
  Routes__13__DownstreamScheme: "http"
  Routes__13__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  Routes__13__DownstreamHostAndPorts__0__Port: "80"
  Routes__14__DownstreamScheme: "http"
  Routes__14__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  Routes__14__DownstreamHostAndPorts__0__Port: "80"
  Routes__15__DownstreamScheme: "ws"
  Routes__15__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-notification-api"
  Routes__15__DownstreamHostAndPorts__0__Port: "80"