apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-webapi
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ReRoutes__0__DownstreamScheme: "http"
  ReRoutes__0__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  ReRoutes__0__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__1__DownstreamScheme: "http"
  ReRoutes__1__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  ReRoutes__1__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__2__DownstreamScheme: "http"
  ReRoutes__2__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-product-api"
  ReRoutes__2__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__3__DownstreamScheme: "http"
  ReRoutes__3__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  ReRoutes__3__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__4__DownstreamScheme: "http"
  ReRoutes__4__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  ReRoutes__4__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__5__DownstreamScheme: "http"
  ReRoutes__5__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-storage-api"
  ReRoutes__5__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__6__DownstreamScheme: "http"
  ReRoutes__6__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  ReRoutes__6__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__7__DownstreamScheme: "http"
  ReRoutes__7__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  ReRoutes__7__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__8__DownstreamScheme: "http"
  ReRoutes__8__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-auditlog-api"
  ReRoutes__8__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__9__DownstreamScheme: "http"
  ReRoutes__9__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  ReRoutes__9__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__10__DownstreamScheme: "http"
  ReRoutes__10__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  ReRoutes__10__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__11__DownstreamScheme: "http"
  ReRoutes__11__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-identity-api"
  ReRoutes__11__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__12__DownstreamScheme: "http"
  ReRoutes__12__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  ReRoutes__12__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__13__DownstreamScheme: "http"
  ReRoutes__13__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  ReRoutes__13__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__14__DownstreamScheme: "http"
  ReRoutes__14__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-configuration-api"
  ReRoutes__14__DownstreamHostAndPorts__0__Port: "80"
  ReRoutes__15__DownstreamScheme: "ws"
  ReRoutes__15__DownstreamHostAndPorts__0__Host: "{{ .Release.Name}}-notification-api"
  ReRoutes__15__DownstreamHostAndPorts__0__Port: "80"