apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-webapi
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Ocelot__DefaultDownstreamScheme: "http"
  Ocelot__Routes__Products__Downstream: "http://{{ .Release.Name}}-product-api"
  Ocelot__Routes__Files__Downstream: "http://{{ .Release.Name}}-storage-api"
  Ocelot__Routes__AuditLogs__Downstream: "http://{{ .Release.Name}}-auditlog-api"
  Ocelot__Routes__Users__Downstream: "http://{{ .Release.Name}}-identity-api"
  Ocelot__Routes__Configurations__Downstream: "http://{{ .Release.Name}}-configuration-api"
  Ocelot__Routes__Hubs__Downstream: "ws://{{ .Release.Name}}-notification-api"