apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-backgroundserver
  name: {{ .Release.Name}}-backgroundserver
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name}}-backgroundserver
status:
  loadBalancer: {}
