version: "3.6"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        networks:
          - kafka-net
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    kafka-server1:
        image: 'bitnami/kafka:latest'
        networks:
          - kafka-net    
        ports:
          - '9092:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper-server
    kafka-server2:
        image: 'bitnami/kafka:latest'
        networks:
          - kafka-net    
        ports:
          - '9093:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9093
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper-server
networks:
    kafka-net:
        driver: bridge