version: "3.6"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
          - zookeeper
        ports:
          - 9092:9092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ubuntu:
        build:
            context: .
            dockerfile: ./ubuntu/Dockerfile
        depends_on:
            - rabbitmq
        command: >
            bash -c " 
            while ! nc -z rabbitmq 15672;
            do
              echo rabbitmq is not ready, sleeping;
              sleep 1;
            done;
            echo Connected!;
            curl -i -u guest:guest -H \""content-type:application/json\"" -XPUT -d '{\""durable\"":true}' http://rabbitmq:15672/api/queues/%2f/classifiedadds_fileuploaded
            && curl -i -u guest:guest -H \""content-type:application/json\"" -XPUT -d '{\""durable\"":true}' http://rabbitmq:15672/api/queues/%2f/classifiedadds_filedeleted
            && curl -i -u guest:guest -H \""content-type:application/json\"" -XPOST -d '{\""routing_key\"": \""classifiedadds_fileuploaded\"", \""arguments\"": {}}' http://rabbitmq:15672/api/bindings/%2f/e/amq.direct/q/classifiedadds_fileuploaded
            && curl -i -u guest:guest -H \""content-type:application/json\"" -XPOST -d '{\""routing_key\"": \""classifiedadds_filedeleted\"", \""arguments\"": {}}' http://rabbitmq:15672/api/bindings/%2f/e/amq.direct/q/classifiedadds_filedeleted
            && echo finished setting up rabbitmq"