version: "3.6"
services:
    identityserver:
        build:
          context: .
          dockerfile: ./ClassifiedAds.IdentityServer/Dockerfile
        ports:
            - "9000:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    notificationserver:
        build:
          context: .
          dockerfile: ./ClassifiedAds.NotificationServer/Dockerfile
        ports:
            - "9001:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    webapi:
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebAPI/Dockerfile
        ports:
            - "9002:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          IdentityServerAuthentication__Authority: "http://host.docker.internal:9000"
          IdentityServerAuthentication__RequireHttpsMetadata: "false"
    webmvc:
        build:
          context: .
          dockerfile: ./ClassifiedAds.WebMVC/Dockerfile
        ports:
            - "9003:80"
        volumes:
            - E:\\files:/files 
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          OpenIdConnect__Authority: "http://host.docker.internal:9000"
          OpenIdConnect__RequireHttpsMetadata: "false"
          ResourceServer__Endpoint: "http://webapi"
          CurrentUrl: "http://localhost:80"
          Storage__Provider: "Local"
          Storage__Local__Path: "/files"
          Storage__Azure__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"
          Storage__Azure__Container: "classifiedadds"
          Storage__Amazon__AccessKeyID: "xxx"
          Storage__Amazon__SecretAccessKey: "xxx"
          Storage__Amazon__BucketName: "classifiedadds"
          Storage__Amazon__RegionEndpoint: "ap-southeast-1"
    backgroundservices:
        build:
          context: .
          dockerfile: ./ClassifiedAds.BackgroundServices/Dockerfile
        ports:
            - "9004:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          NotificationServer__Endpoint: "http://notificationserver"
    grpc:
        build:
          context: .
          dockerfile: ./ClassifiedAds.GRPC/Dockerfile
        ports:
            - "9005:443"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ASPNETCORE_URLS: "https://+"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
    graphql:
        build:
          context: .
          dockerfile: ./ClassifiedAds.GraphQL/Dockerfile
        ports:
            - "9006:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
          GrpcService__Endpoint: "https://grpc"
    ocelot:
        build:
          context: .
          dockerfile: ./ClassifiedAds.Ocelot/Dockerfile
        ports:
            - "9007:80"
        environment:
          ASPNETCORE_ENVIRONMENT: "Docker"
          ConnectionStrings__ClassifiedAds: "Server=host.docker.internal;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true"
